# Generated by Django 4.2 on 2023-05-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('codeAS', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('annee_scolaire', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('codeC', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('1ere Année', '1ere Année'), ('2eme Année', '2eme Année'), ('3eme Année', '3eme Année')], max_length=30)),
                ('classe', models.CharField(max_length=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.anneescolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DS1', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('DS2', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('exam', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.PositiveIntegerField(default=0)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('sexe', models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='etudiant')),
                ('ecole_origine', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=120, null=True)),
                ('nom_du_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_pere', models.CharField(blank=True, max_length=70, null=True)),
                ('nom_de_la_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_mere', models.CharField(blank=True, max_length=70, null=True)),
                ('adresse_des_parents', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_du_correspondant', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_correspondant', models.CharField(blank=True, max_length=70, null=True)),
                ('adresse_des_correspondant', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_de_frere', models.PositiveIntegerField(default=0)),
                ('nombre_de_soeur', models.PositiveIntegerField(default=0)),
                ('rang_dans_la_famille', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('sport_preferer', models.CharField(blank=True, max_length=70, null=True)),
                ('sport_pratique', models.CharField(blank=True, max_length=70, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('codeF', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('filiere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('1ere Année', '1ere Année'), ('2eme Année', '2eme Année'), ('3eme Année', '3eme Année')], max_length=30)),
                ('coeff', models.PositiveIntegerField(default=1)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.matier')),
            ],
            options={
                'unique_together': {('filiere', 'niveau', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('codeP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('codeSect', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('secteur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('codeTF', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_formation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_matiere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.classe')),
                ('etudiant', models.ManyToManyField(through='web.Contenir', to='web.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.periode')),
            ],
            options={
                'unique_together': {('annee_scolaire', 'classe', 'periode')},
            },
        ),
        migrations.AddField(
            model_name='matier',
            name='type_matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.typematiere'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.secteur'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.etudiant'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.note'),
        ),
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.filiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='type_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.typeformation'),
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('note', 'etudiant')},
        ),
        migrations.CreateModel(
            name='Abs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_abscence', models.PositiveIntegerField(default=0)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.anneescolaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.etudiant')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.periode')),
            ],
            options={
                'unique_together': {('periode', 'etudiant', 'annee_scolaire')},
            },
        ),
    ]
