# Generated by Django 4.2.1 on 2023-05-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_note_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='position',
            field=models.CharField(choices=[('Passant', 'Pasant(e)'), ('Redoublant', 'Redoublant(e)'), ('TRP', 'Tansfert Passant'), ('TRR', 'Transfert Redoublant')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
