# Generated by Django 4.2.1 on 2023-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_etudiant_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='position',
            field=models.CharField(choices=[('P', 'Pasant(e)'), ('R', 'Redoublant(e)'), ('TRP', 'Tansfert Passant'), ('TRR', 'Transfert Redoublant')], max_length=100),
        ),
    ]
