# Generated by Django 4.2.1 on 2023-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_classe_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChefDeTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Feminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=20)),
            ],
        ),
    ]
