# Generated by Django 4.2.1 on 2023-06-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_contenir_ds2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censeur',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='proviseur',
            name='sexe',
        ),
    ]
