# Generated by Django 4.2.1 on 2023-06-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_censeur_sexe_remove_proviseur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='DS2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
