# Generated by Django 4.2.1 on 2023-06-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_contenir_ds2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='DS2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
