# Generated by Django 4.2.1 on 2023-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_etudiant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_joindre',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
