# Generated by Django 4.2.1 on 2023-08-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_contenir_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='observation',
        ),
    ]
