# Generated by Django 4.2.1 on 2023-08-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_remove_contenir_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='codeAS',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periode',
            name='codeP',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
